# Generated by Django 3.2.9 on 2021-12-06 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayAlcoholList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('alcohol_degree', models.IntegerField(verbose_name='アルコール度数')),
                ('amount', models.CharField(choices=[('', ''), ('大', '大ジョッキ(約500ml)'), ('中', '中ジョッキ、チューハイ等(約350ml)'), ('小', '小ジョッキ(約200ml)'), ('グラス', 'グラス(約125ml)'), ('ロック', 'ロック(約60ml)'), ('おちょこ', 'おちょこ(約45ml)'), ('シングル', 'シングル(約30ml)'), ('ダブル', 'ダブル(約60ml)')], max_length=50, verbose_name='サイズ')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '素面'), ('1', 'ほんのり酔ってきた'), ('2', '酔っぱらった'), ('3', '世界が歪んで見える'), ('4', '限界です')], max_length=30, verbose_name='酔っ払い度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrankAlcoholList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drank_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drank_cards', to='sake_log.displayalcohollist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
