# Generated by Django 3.2.9 on 2022-01-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sake_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drankalcohollist',
            name='drank_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drank_cards', to='sake_log.displayalcohollist'),
        ),
    ]
