# Generated by Django 3.2.9 on 2022-01-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sake_log', '0002_alter_drankalcohollist_drank_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drankalcohollist',
            name='drank_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drank_cards', to='sake_log.displayalcohollist'),
        ),
    ]
