# Generated by Django 3.2.9 on 2022-01-08 02:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sake_log', '0007_alter_drankalcohollist_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrankAlcoholList',
            new_name='AlcoholLogList',
        ),
    ]
