# Generated by Django 3.2.9 on 2022-01-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sake_log', '0008_rename_drankalcohollist_alcoholloglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='AlcoholLogList', # モデル名
            old_name='drank_card',   # 変更前
            new_name='alcohol'    # 変更後
        )
    ]
